name: Python package

on:
  push:
    branches:
      - main # Trigger on any push to the main branch
  pull_request:
    branches:
      - main # Trigger on PRs targeting main (created or updated)
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [3.9, '3.10', 3.11]
        python-version: [3.9, 3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run Black
        run: poetry run black --check .
      - name: Run Flake8
        run: poetry run flake8 .
      - name: Run tests
        run: poetry run pytest
